### ISSUE TITLE
Other events

### ISSUE THREAD

**Issue by hong4rc** [nomi-san/yasuo#2]
You send `[5,"OnJsonApiEvent"]`

Do you know other events to listen more event.

Thank you

**Comment by nomi-san** [comment]
You can use **IDA Pro** to explore more event.
a few events I found: OnCallback, OnClientConfigEvent, OnLog etc

```json
[5, "OnLog"]    // subscribe OnLog
[6, "OnLog"]    // unsubscribe
```

**Comment by hong4rc** [comment]
@nomi-san How to catch request to the port of game?

I used `mitmproxy` to create a local proxy. I can catch normally request(website in browser), but it cannot catch request of LoL app

**Comment by nomi-san** [comment]
"game/LoL app", is this in game? Impossible.
You only can request to LCU/RTMP via HTTPS client, and subscribe to callback event via websocket (must reject TSL/SSL).

On web browser, you need build a websocket for request core (backend side).
For example, [Mimic](https://github.com/molenzwiebel/Mimic) app structure
- [Web](https://github.com/molenzwiebel/Mimic/blob/master/web) is the user interface presented to users. It uses Vue with Typescript and handles the actual controlling of the client.
- [Conduit](https://github.com/molenzwiebel/Mimic/blob/master/conduit) is the Windows application that redirects client traffic to the mobile website. It is written in C# and uses Websockets to connect to both the LCU and the mobile client.
